export const ACTION_ADD_SCORE = "ACTION_ADD_SCORE";
export const ACTION_RESET_SCORE = "ACTION_RESET_SCORE";
export const ACTION_RESET_GAME = "ACTION_RESET_GAME";

export const ACTION_ADD_SCORE_TO_HISTORY = "ACTION_ADD_SCORE_TO_HISTORY";
